- name: Build with Gradle
        run: |
          # Gọi trực tiếp task assemble thay vì build để ép nó tạo APK
          if [ "${{ github.event.inputs.build_type }}" == "debug" ]; then
            ./gradlew assembleDebug --stacktrace
          else
            ./gradlew assembleRelease --stacktrace
          fi

      - name: Find and Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ZalithLauncher-APK
          # Thay đổi path này để GitHub tìm trong mọi thư mục con
          path: |
            **/build/outputs/apk/debug/*.apk
            **/build/outputs/apk/release/*.apk
